CREATE VIEW VIEWCLIENTESORTEADOS (CODIGOCLIENTE, NOMECLIENTE, CLIENTE)AS
WITH SORTEIO_CLIENTES
AS (SELECT CLI.CODIGO, CLI.NOME, CLI.CPF_CNPJ
    FROM CLIENTES CLI
    JOIN VENDAS VEN ON (VEN.CODCLIENTE = CLI.CODIGO)
    JOIN VEICULOS VEI ON (VEI.CODIGO = VEN.CODVEICULO)
    WHERE (CHAR_LENGTH(CLI.CPF_CNPJ) = 11 AND
          CLI.CPF_CNPJ LIKE '0%') AND
          VEI.ANOLANCAMENTO = 2021)

SELECT FIRST 15 S.*
FROM SORTEIO_CLIENTES S
WHERE (SELECT COUNT(*)
       FROM VENDAS VEN, VEICULOS VEI, MODELOSVEICULO MDV
       WHERE VEN.CODVEICULO = VEI.CODIGO AND
             VEI.CODMODELO = MDV.CODIGO AND
             VEN.CODCLIENTE = S.CODIGO AND
             UPPER(MDV.MODELO) = 'MAREA') <> 2;