DROP VIEW viewclientesorteados;
DROP TABLE VENDAS;
DROP TABLE VEICULOS;
DROP TABLE CLIENTES;
DROP SEQUENCE GENCODCLIENTE;
DROP SEQUENCE GENCODVEICULO;
DROP SEQUENCE GENCODVENDA;

CREATE TABLE CLIENTES(
CODIGO INTEGER NOT NULL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF_CNPJ VARCHAR(14) NOT NULL
);

CREATE GENERATOR GENCODCLIENTE;
SET GENERATOR GENCODCLIENTE TO 0;

CREATE TRIGGER TRGNOVOCODIGOCLIENTE FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
    NEW.CODIGO = GEN_ID(GENCODCLIENTE, 1);
END;


CREATE TABLE VEICULOS (
CODIGO INTEGER NOT NULL PRIMARY KEY,
MODELO VARCHAR(50) NOT NULL,
ANOLANCAMENTO INTEGER NOT NULL
);
CREATE GENERATOR GENCODVEICULO;
SET GENERATOR GENCODVEICULO TO 0;

CREATE TRIGGER TRGNOVOCODIGOVEICULO FOR VEICULOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
    NEW.CODIGO = GEN_ID(GENCODVEICULO, 1);
END;

CREATE TABLE VENDAS (
CODIGO INTEGER NOT NULL PRIMARY KEY,
CODCLIENTE INTEGER NOT NULL,
CODVEICULO INTEGER NOT NULL,
DATAVENDA TIMESTAMP
);
CREATE GENERATOR GENCODVENDA;
SET GENERATOR GENCODVENDA TO 0;

CREATE TRIGGER TRGNOVOCODIGOVENDA FOR VENDAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
    NEW.CODIGO = GEN_ID(GENCODVENDA, 1);
END;

ALTER TABLE VENDAS ADD CONSTRAINT FK_RLC_VENDA_CLIENTE FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES (CODIGO);
ALTER TABLE VENDAS ADD CONSTRAINT FK_RLC_VENDA_VEICULO FOREIGN KEY (CODVEICULO) REFERENCES VEICULOS (CODIGO);



/*VIEW COM CLIENTE SORTEADOS DE ACORDO COM AS REGRAS*/
CREATE VIEW VIEWCLIENTESORTEADOS (CODIGOCLIENTE, NOMECLIENTE, CLIENTE)AS
WITH SORTEIO_CLIENTES
AS (SELECT CLI.CODIGO, CLI.NOME, CLI.CPF_CNPJ
    FROM CLIENTES CLI
    JOIN VENDAS VEN ON (VEN.CODCLIENTE = CLI.CODIGO)
    JOIN VEICULOS VEI ON (VEI.CODIGO = VEN.CODVEICULO)
    WHERE (CHAR_LENGTH(CLI.CPF_CNPJ) = 11 AND CLI.CPF_CNPJ LIKE '0%')
      AND VEI.ANOLANCAMENTO = 2021)

SELECT FIRST 15 S.*
FROM SORTEIO_CLIENTES S
WHERE (SELECT COUNT(*)
       FROM VENDAS VEN, VEICULOS VEI
       WHERE VEN.CODVEICULO = VEI.CODIGO AND
             VEN.CODCLIENTE = S.CODIGO AND
             UPPER(VEI.MODELO) = 'MAREA') <> 2;
